config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :questions, only: [:index, :show]

  resources :results, only: [:index]
end

app/models/answer.rb
class Answer < ApplicationRecord
    validates_presence_of :response
    validates :correct?, inclusion: [true, false]
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates_presence_of :ask
    has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def index
        if params[:quiz_ids]
            quiz_ids = params[:quiz_ids]
        else
            questions = Question.take(10)
            quiz_ids = questions.map { |question| question.id }
        end
        current_question = Question.find(quiz_ids.first)
        quiz_ids.shift
        if current_question
            redirect_to question_path(current_question.id, quiz_ids)
        else
            redirect_to results_path
        end
    end

    def show
        @current_question = Question.find(params[:id])
        @current_answers = @current_question.answers
    end

    private

    def question_params
        params.permit(:id, :quiz_ids)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    
    def index
        
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TandemTrivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/show.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>Question:</h1>

<h2><%= @current_question.ask %></h2>

<h3>Select your answer below and click "Submit"</h3>

<%= form_tag("/questions/#{@current_question.id}/answer", method: :post) do %>
    <% @current_answers.each do |answer| %>
        <%= answer.response %>%= radio_button_tag "correct", answer.correct? %>
    <% end %>
<% end %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>Welcome to Tandem Trivia!</h1>

    
<p>
    At Tandem, playing trivia isn't just a fun way to learn something new, but also a great way to take a little break from a normal work task.
    While everyone is knowledgeable in their own right, only one person can be crowned trivia champion with the highest score.
    This application will help you practice and improve your Tandem Trivia skills.
</p>

<p>
    Click on the 'Take Quiz' button to begin the quiz. You will be given 10 Tandem-related questions.
    After each question, you will be shown the correct answer.
    At the end of the quiz, you will be shown your cumulative score.
    Good luck!
</p>

<%= button_to 'Take Quiz', questions_path, method: :get %>

</body>
</html>